name: power3d_annotations
publish_to: none
description: "A collection of annotation styles for Power3D plugin."
version: 0.0.1
homepage: https://github.com/rashbip/power_3d

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  power3d:
    path: ../power3d

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/styles/textcallout.js
    - assets/styles/hotspot.js
