name: power3d_annotations
# publish_to: none
description: "A collection of annotation styles for Power3D plugin."
version: 1.0.0
homepage: https://github.com/rashbip/power3d_annotations

screenshots:
  - description: "Clean, minimalist 3D hotspots"
    path: docs/screenshots/hotspot.jpg
  - description: "Interactive HTML-based text callouts"
    path: docs/screenshots/callout.jpg

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  power3d: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/styles/textcallout.js
    - assets/styles/hotspot.js
